server:
  port: 9005

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/ecomapp
    username: postgres
    password: admin
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

  application:
    name: order-service

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://ecom-service-registry:8761/eureka/
  instance:
    prefer-ip-address: true