spring:
  datasource:
    url: jdbc:postgresql://postgres:5432/ecomapp

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://ecom-service-registry:8761/eureka/
  instance:
    prefer-ip-address: true